[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@uniswap/v3-core/=lib/v3-core",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
  "@forge-std/=lib/forge-std",
  "@uniswap/v3-periphery/=lib/v3-periphery",
]
